# -*- coding: utf-8 -*-
"""Projeto_Agente_exercicio_pilates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mwqwUkUctEJ1xSx1oY7SDSLN4MNO16xF
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip -q install google-genai

# Configura a API Key do Google Gemini
import os
from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_YOUR_API_KEY')

# Configura o cliente da SDK do Gemini
from google import genai
client = genai.Client()
MODEL_ID = "gemini-2.0-flash"

# Pergunta ao Gemini uma informação mais recente que seu conhecimento

from IPython.display import HTML, Markdown

# Perguntar pro modelo quando é a próxima imersão de IA ###############################################
resposta = client.models.generate_content(
    model = MODEL_ID,
    contents = "Quando é a próxima Imersão IA com Google Gemini do Alura?"
)

# Exibe a resposta na tela
display(Markdown(f"Resposta:\n {resposta.text}"))

# Commented out IPython magic to ensure Python compatibility.
# Instalar Framework ADK de agentes do Google ################################################
# %pip -q install google-adk

from google.adk.agents import Agent
from google.adk.runners import Runner
from google.adk.sessions import InMemorySessionService
from google.adk.tools import google_search
from google.genai import types  # Para criar conteúdos (Content e Part)
from datetime import date
import textwrap # Para formatar melhor a saída de texto
from IPython.display import display, Markdown # Para exibir texto formatado no Colab
import requests # Para fazer requisições HTTP
import warnings
import json # Importação do módulo json (correção do erro anterior)

warnings.filterwarnings("ignore")

# Função auxiliar que envia uma mensagem para um agente via Runner e retorna a resposta final
def call_agent(agent: Agent, message_text: str) -> str:
    # Cria um serviço de sessão em memória
    session_service = InMemorySessionService()
    # Cria uma nova sessão (você pode personalizar os IDs conforme necessário)
    session = session_service.create_session(app_name=agent.name, user_id="user1", session_id="session1")
    # Cria um Runner para o agente
    runner = Runner(agent=agent, app_name=agent.name, session_service=session_service)
    # Cria o conteúdo da mensagem de entrada
    content = types.Content(role="user", parts=[types.Part(text=message_text)])

    final_response = ""
    # Itera assincronamente pelos eventos retornados durante a execução do agente
    for event in runner.run(user_id="user1", session_id="session1", new_message=content):
        if event.is_final_response():
            for part in event.content.parts:
                if part.text is not None:
                    final_response += part.text
                    final_response += "\n"
    return final_response

# Função auxiliar para exibir texto formatado em Markdown no Colab
def to_markdown(text):
  text = text.replace('•', '  *')
  return Markdown(textwrap.indent(text, '> ', predicate=lambda _: True))

##########################################
# --- Agente 1: Buscador de Notícias --- #
##########################################
def agente_buscador(exercicio):
    buscador = Agent(
        name = "agente_buscador",
        model = "gemini-2.0-flash",
        instruction="""
        Você é um assistente de pesquisa. Sua tarefa é usar a ferramenta de busca do Google
        (google_search) para recuperar informações confiáveis para a execução do exercício de pilates
        de forma segura. Foque em canais confiáveis e de reputação comprovada que
        informem detalhes do exercício pesquisado. Busque 10 sites mais
        relevantes sobre o exercício de pilates buscado.
        """,
        description="Agente que busca informações sobre notícias no Google",
        tools = [google_search]
)

    entrada_do_agente_buscador = f"Exercício de pilates: {exercicio}"
    informacoes = call_agent(buscador, entrada_do_agente_buscador)
    return informacoes

################################################
# --- Agente 2: Planejador de posts --- #
################################################
def agente_planejador(exercicio, informacoes_buscadas):
    planejador = Agent(
        name="agente_planejador",
        model="gemini-2.0-flash",
        # Inserir as instruções do Agente Planejador #################################################
        instruction="""
        Você é um planejador de conteúdo, especialista em aplicativos para celular sobre exercícios físicos.
        Com base nos sites obtidos pelo buscador em sites especializados, você deve:
        usar a ferramenta de busca do Google (google_search) para criar um plano sobre quais são os
        pontos mais importantes na execução do exercício de pilates para três
        níveis de usuários: iniciante, intermediário e avançado de pilates.
        Você também pode usar o (google_search) para encontrar mais informações sobre a execução do exercício e
        aprofundar nas orientações para cada nível de usuário. Ao final, você colocará em tópicos o passo-a-passo para a execução precisa do
        exercício de pilates com base nas suas pesquisas e retornar
        os níveis básico, intermediário e avançado a serem abordados nos cards, que serão escritos posteriormente. Os cards devem ser pensados
        progressivamente para os três níveis de usuários.
        """,
        description="Agente que planeja posts",
        tools=[google_search]
    )

    entrada_do_agente_planejador = f"Exercício {exercicio} de pilates: {informacoes_buscadas}"
    # Executa o agente
    plano_do_post = call_agent(planejador, entrada_do_agente_planejador)
    return plano_do_post

##########################################
# --- Agente 3: Redator de Cards --- #
##########################################
def agente_redator(exercicio, plano):
    redator = Agent(
        name="agente_redator",
        model="gemini-2.5-flash-preview-04-17",
        instruction=f"""
            Você é um Redator especializado em criar cards para aplicativos mobile de exercícios físicos.
            Utilize as informações fornecidas no plano de cards e os tópicos fornecidos e, com base nisso,
            escreva um rascunho de cards para o aplicativo sobre o exercício abordado nos três níveis de usuários
             (básico, intermediário e avançado em pilates). O nome do exercício deve ser mantido como
             originalmente solicitado {exercicio} mas a linguagem dos cards deve ser em português.

            Cada card deve conter:
            - 'titulo': O título é o exercício solicitado card.
            - 'base': Informações de nível básico do exercício.
            - 'topicos': Uma lista de como o exercício deve ser realizado.
            - 'modificacoes': Se aplicável, detalhes sobre modificações ou variações do exercício.
            - 'progressoes': Se aplicável, detalhes para progressões e variações do exercício para nível intermediário e avançado.
            - 'erros_comuns': Se aplicável, os erros comuns mencionados e seus ajustes para cada nível.

            As instruções devem ser precisas. Importante salientar a respiração e o músculo a ser trabalhado. O público é exigente,
            necessitando de detalhes precisos e informativos. Crie os cards seguindo rigorosamente o plano fornecido, mas sucinto e
            adequado para a visualização em um aplicativo mobile. Se necessário, crie cards extras para modificações e progressões.
            As informações de erros comuns devem aparecer em cada card.
            Inicie cada card com o seguinte:
            Cada card DEVE começar com o indicador:

            '***INÍCIO DO CARD***'

            E cada card DEVE terminar com o indicador:
            '***FIM DO CARD***'

           """,
        description="Agente para redigir cards de exercícios de Pilates."
    )
    entrada_do_agente_redator = f"Por favor, gere os cards de Pilates para o {exercicio} seguindo este plano: {plano}."
    rascunho = call_agent(redator, entrada_do_agente_redator)
    return rascunho

##########################################
# --- Agente 4: Revisor de Qualidade --- #
##########################################
def agente_revisor(exercicio, rascunho_gerado):
    revisor = Agent(
        name="agente_revisor",
        model="gemini-2.5-flash-preview-04-17",
        instruction="""
            Você é um Editor e Revisor de Conteúdo meticuloso, especializado em cards para aplicativos de exercícios físicos,
            com foco em público prático e experiente, necessitando de detalhes precisos e informativos.
            Use um tom de escrita adequado.
            Revise o rascunho dos cards sobre o exercício indicado, verificando o detalhamento do exercício para cada nível
            de usuário (iniciante em pilates, intermediário em pilates, experiente em pilates) com clareza, concisão, correção e tom.
            Cada card começa com o indicador:

            '***INÍCIO DO CARD***'

            E cada card termina com o indicador:
            '***FIM DO CARD***'

            Se o rascunho estiver bom, responda apenas 'O rascunho está ótimo e pronto para publicar!'.
            Caso haja problemas, aponte-os e sugira melhorias.
            """,
        description="Agente revisor de post para redes sociais."
    )
    entrada_do_agente_revisor = f"Exercício: {exercicio}\nRascunho: {rascunho_gerado}"
    # Executa o agente
    texto_revisado = call_agent(revisor, entrada_do_agente_revisor)
    return texto_revisado

print("🚀 Iniciando o Sistema de Criação de Cards para Aplicativos de Celular para Exercícios de Pilates com 5 Agentes 🚀")

# --- Obter o Tópico do Usuário ---
exercicio = input("❓ Por favor, digite o EXERCÍCIO DE PILATES sobre o qual você quer criar os cards: ")

# Inserir lógica do sistema de agentes ################################################
if not exercicio:
  print("Você esqueceu de digitar o exercício")
else:
  print(f"Maravilha! Vamos então criar os cards com os tópicos principais sobre o exercício {exercicio} de pilates!")

informacoes_buscadas = agente_buscador(exercicio)
print("\n --- 📝 Resultado do Agente 1 - (Buscador) ---\n")
display(to_markdown(informacoes_buscadas))
print("--------------------------------------------------")

plano_de_cards = agente_planejador(exercicio, informacoes_buscadas)
print("\n --- 📝 Resultado do Agente 2 - (Planejador) ---\n")
display(to_markdown(plano_de_cards))
print("--------------------------------------------------")

rascunho_de_cards = agente_redator(exercicio, plano_de_cards)
print("\n --- 📝 Resultado do Agente 3 - (Redator) ---\n")
display(to_markdown(rascunho_de_cards))
print("--------------------------------------------------")

cards_revisados = agente_revisor(exercicio, rascunho_de_cards)
print("\n --- 📝 Resultado do Agente 4 - (Revisor) ---\n")
display(to_markdown(cards_revisados))
print("--------------------------------------------------")